#!/usr/bin/env bash
# PR Review Skill - Automated pull request review script
# Analyzes code changes, checks for common issues, and posts review comments

set -euo pipefail

# ─── Configuration ────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"

# Required environment variables
REQUIRED_VARS=("GITHUB_TOKEN" "GITHUB_REPOSITORY" "PR_NUMBER")

# ─── Helpers ──────────────────────────────────────────────────────────────────
log()  { echo "[pr-review] $*"; }
err()  { echo "[pr-review] ERROR: $*" >&2; }
die()  { err "$*"; exit 1; }

check_required_vars() {
  for var in "${REQUIRED_VARS[@]}"; do
    if [[ -z "${!var:-}" ]]; then
      die "Required environment variable '$var' is not set."
    fi
  done
}

check_dependencies() {
  local deps=("gh" "jq" "git")
  for dep in "${deps[@]}"; do
    if ! command -v "$dep" &>/dev/null; then
      die "Required dependency '$dep' is not installed."
    fi
  done
}

# ─── GitHub helpers ───────────────────────────────────────────────────────────
get_pr_files() {
  gh api \
    -H "Accept: application/vnd.github+json" \
    "/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/files" \
    | jq -r '.[].filename'
}

get_pr_diff() {
  gh pr diff "$PR_NUMBER" --repo "$GITHUB_REPOSITORY"
}

get_pr_metadata() {
  gh pr view "$PR_NUMBER" \
    --repo "$GITHUB_REPOSITORY" \
    --json title,body,author,baseRefName,headRefName,additions,deletions,changedFiles
}

post_review_comment() {
  local body="$1"
  local event="${2:-COMMENT}"  # COMMENT | APPROVE | REQUEST_CHANGES

  gh pr review "$PR_NUMBER" \
    --repo "$GITHUB_REPOSITORY" \
    --"$(echo "$event" | tr '[:upper:]' '[:lower:]' | tr '_' '-')" \
    --body "$body"
}

# ─── Analysis ─────────────────────────────────────────────────────────────────
check_test_coverage() {
  local changed_files="$1"
  local missing_tests=()

  while IFS= read -r file; do
    # Check if source file has a corresponding test file
    if [[ "$file" =~ ^src/.*\.py$ ]]; then
      local test_file
      test_file="tests/$(echo "$file" | sed 's|^src/||; s|\.py$|_test.py|')"
      if ! echo "$changed_files" | grep -q "$test_file"; then
        missing_tests+=("$file")
      fi
    fi
  done <<< "$changed_files"

  if [[ ${#missing_tests[@]} -gt 0 ]]; then
    log "Files potentially missing test coverage: ${missing_tests[*]}"
    echo "${missing_tests[@]}"
  fi
}

check_large_diff() {
  local additions="$1"
  local deletions="$2"
  local total=$(( additions + deletions ))

  if (( total > 500 )); then
    echo "This PR changes $total lines ($additions additions, $deletions deletions). Consider splitting into smaller PRs for easier review."
  fi
}

build_review_summary() {
  local metadata changed_files warnings
  metadata="$(get_pr_metadata)"
  changed_files="$(get_pr_files)"

  local additions deletions changed_file_count
  additions=$(echo "$metadata" | jq '.additions')
  deletions=$(echo "$metadata" | jq '.deletions')
  changed_file_count=$(echo "$metadata" | jq '.changedFiles')

  log "PR #${PR_NUMBER}: +${additions}/-${deletions} across ${changed_file_count} file(s)"

  warnings=""

  # Check for large diffs
  local large_diff_msg
  large_diff_msg="$(check_large_diff "$additions" "$deletions")"
  if [[ -n "$large_diff_msg" ]]; then
    warnings+="\n⚠️  **Large diff**: $large_diff_msg"
  fi

  # Check for missing tests
  local missing_tests
  missing_tests="$(check_test_coverage "$changed_files")"
  if [[ -n "$missing_tests" ]]; then
    warnings+="\n⚠️  **Possible missing tests** for: $(echo "$missing_tests" | tr ' ' ', ')"
  fi

  # Build summary body
  local body
  body="## 🤖 Automated PR Review\n"
  body+="**Changed files**: ${changed_file_count} | **Additions**: +${additions} | **Deletions**: -${deletions}\n\n"

  if [[ -n "$warnings" ]]; then
    body+="### Warnings\n${warnings}\n"
  else
    body+="✅ No automated warnings found.\n"
  fi

  body+="\n*Review generated by the pr-review skill. Please verify findings manually.*"
  echo -e "$body"
}

# ─── Main ─────────────────────────────────────────────────────────────────────
main() {
  log "Starting PR review for PR #${PR_NUMBER} in ${GITHUB_REPOSITORY}"

  check_required_vars
  check_dependencies

  local review_body
  review_body="$(build_review_summary)"

  log "Posting review comment..."
  post_review_comment "$review_body" "COMMENT"

  log "PR review complete."
}

main "$@"
